name: Build Flet APK
on:
  push:
    branches: [ main ]
  workflow_dispatch: # Позволяет запускать сборку вручную

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flet

      - name: Build APK
        run: |
          # Flet build apk создаст бинарный файл
          flet build apk

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: flet-app-apk
          path: build/apk/*.apk